# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeeClickFixCodeTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SeeClickFixCodeTest

  pod ‘TwitterKit’

  target 'SeeClickFixCodeTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeeClickFixCodeTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
